# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  config.vm.provision "shell", path: "setup"

  config.vm.network :forwarded_port, guest: 80, host: 3000   #HTTP
  # config.vm.network :forwarded_port, guest: 8081, host: 443  #HTTPS
  # config.vm.network :forwarded_port, guest: 6379, host: 6379 #REDIS
  # config.vm.network :forwarded_port, guest: 3306, host: 3307

  # private_network is on virtual host-only network
  # config.vm.network :private_network, ip: "192.168.33.10"

  # public_network appears like new computer on your network
  config.vm.network :public_network
end
